### ISSUE TITLE
git 和 format 时使用

### ISSUE THREAD

**Issue by liuzhihang** [LiLittleCat/intellij-pangu#2]
感谢，发现下载量竟然是 0 ，使用了，之前一直用 vscode 的 pangu 格式化博客 markdown，现在在 idea 里面也有了。提点小建议：

在 git 提交时可以选择使用 pangu 格式化，以及在格式化代码时也自动使用。

**Comment by LiLittleCat** [comment]
@liuzhihang 感谢使用，下载量是 0 是因为昨天才上线呢，我也是搜插件市场没有，所以自己写了一个。你的建议不错，我看看怎么实现，抽空给他加上。:smile:

**Comment by LiLittleCat** [comment]
@liuzhihang 功能已经添加，请更新插件版本至 v1.1.0  使用，谢谢。
