### ISSUE TITLE
""内含中文，格式化后会加空格

### ISSUE THREAD

**Issue by Ya-RZ** [LiLittleCat/intellij-pangu#20]
格式化前:
```rust
let origin = "张三".as_bytes();
let origin = "张三D".as_bytes();
let key = "ABC".as_bytes();
```
格式化后：
```rust
let origin = " 张三 ".as_bytes();  //加空格了，错误
let origin = " 张三 D".as_bytes();  //加空格了，错误
let key = "ABC".as_bytes(); //没加空格，正确
```

版本：1.2.2
语言：Rust
这个插件是不是只应该处理勾选的或者注释？正常代码里的免不了CJK和英文混杂，而正常代码可以使用软件默认的格式化。

**Comment by LiLittleCat** [comment]
@sprders 你好，感谢反馈。这个问题之前我发现了：#7，但是可能只改了英文。
> 这个插件是不是只应该处理勾选的或者注释？正常代码里的免不了CJK和英文混杂，而正常代码可以使用软件默认的格式化。

你可以通过选中部分内容进行格式化，但目前没有区分是否是注释，我抽空看看好不好实现。

**Comment by NextAlone** [comment]
Hi, 希望有时间的话尽快处理一下这个, pangu的功能还是很需要的, 字符串里的中文看下怎么能够不处理, 感谢

**Comment by LiLittleCat** [comment]
@sprders @NextAlone 感谢提醒，太忙还真给忘了。目前打算将代码中经常出现的英文引号（如`"`，`'`）包围的内容不进行 `Pangu` ，如果在注释中也出现引号包围，认为其为特殊内容，不进行 `Pangu` 。本来是想获取注释来进行 `Pangu` 的，但像 markdown 文件之类的非代码文件，其本身的内容就是 `Pangu` 的对象。总之，场景挺多，得慢慢补充。最后，感谢使用，新版本将尽快上线。:smile_cat:

**Comment by NextAlone** [comment]
问下，Plugins MarketPlace 多久会上线啊，action走完就好了吗？

**Comment by LiLittleCat** [comment]
@NextAlone 看 JetBrains 审核，应该一两天吧，急用的话等会儿从 release 里下载本地安装。
